version: '3'


services:
  app:
    container_name: nicegui
    hostname: nicegui
    image: quay.io/thikade/kubeseal-web:v1.0
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    ports:
        - 8080:8080
    volumes:
        - ./app/:/app/:ro
        - ./k8s/envs/demo/files/:/config/:ro