apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets

resources:
- ../../base

configMapGenerator:
- name: kubeseal-config
  files:
    - files/config.yaml

images:
- name: kubeseal-web
  newName: ghcr.io/alpium-it/kubeseal-web
  newTag: v1.1.3