name: build & push

on:
  workflow_dispatch:
  push:
    tags:
      - v**

env:
  ENV_FILE: .env
  REGISTRY: ghcr.io
  COMPOSE_OPTS: -f docker-compose.yml
  SRC_BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  TGT_BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Load env vars
        run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: Get short commit SHA
        id: vars
        run: |
          echo "COMMIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: debug.print
        run: |
          echo "Dependencies: "
          echo "   NICEGUI_VERSION:  $NICEGUI_VERSION"
          echo "   KUBESEAL_VERSION: $KUBESEAL_VERSION"
          echo "---"
          echo "GITHUB_EVENT: ${{ github.event_name }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "COMMIT_SHA_SHORT: $COMMIT_SHA_SHORT"
          echo "SRC_BRANCH_NAME: $SRC_BRANCH_NAME"
          echo "TGT_BRANCH_NAME: $TGT_BRANCH_NAME"

      - name: Pushing ENABLED
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "Pushing because ref is a tag"

      - name: Pushing DISABLED
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "not pushing because ref is not a tag"

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate metadata (tags, labels) for container image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: debug.print metadata
        run: |
          echo "TAGS:   ${{ steps.meta.outputs.tags }}"
          echo "LABELS: ${{ steps.meta.outputs.labels }}"


      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            NICEGUI_VERSION=${{ env.NICEGUI_VERSION }}
            KUBESEAL_VERSION=${{ env.KUBESEAL_VERSION }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}



      # ========================================================
      # use docker compose instead of docker build

      # - name: Build image
      #   run: docker compose ${{ env.COMPOSE_OPTS }} build

      # - name: Push image
      #   if: ${{ startsWith(github.ref, 'refs/tags/') }}
      #   run: docker compose ${{ env.COMPOSE_OPTS }} push
